web:
  children:
    app

app:
  hosts:
    vagrant_host:
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: /Users/ev-ivanoff/devopsITMO/.vagrant/machines/srv1/virtualbox/private_key
