---
  - name: Add Docker GPG apt Key
    apt_key:
      url: "{{ docker_apt_gpg_key_url }}"
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: "{{ docker_apt_repository_url }}"
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: docker
