---
# defaults file for postgresql
postgresql_master_group_name: db_master
postgresql_replica_group_name: db_replica
postgresql_master_address: "192.168.56.201"
postgresql_replica_address: 
  - "192.168.56.202"
postgresql_replica_user: replica
postgresql_replica_password: root
postgresql_data_dir: /var/lib/postgresql/12/main
postgresql_custom_data_dir: /home/vagrant/postgresql
postgresql_conf_dir: /etc/postgresql/12/main/
postgresql_database_list:
  - test_db1
  - test_db2
postgresql_user_list: 
  - { name: user1, password: user1user1 }
  - { name: user2, password: user2user2 }
postgresql_user_database_list:
  - { db: test_db1, user: user1 }
  - { db: test_db2, user: user2 }
