---
  - name: Installing openvpn packages
    apt:
      pkg:
        - openvpn
        - easy-rsa
        - iptables-persistent
      state: present
      update_cache: yes
    notify: enable openvpn

  - name: "Create {{ openvpn_dir }}/easy-rsa if not exists"
    file:
      path: "{{ openvpn_dir }}/easy-rsa"
      state: directory
      mode: 0755

  - name: Easyrsa init-pki
    command:
      cmd: "{{ easy_rsa_dir }}/easyrsa init-pki"
      chdir: "{{ openvpn_dir }}/easy-rsa"
      creates: "{{ openvpn_dir }}/easy-rsa/pki"

  - name: easy-rsa build-ca
    command: 
      cmd: "{{ easy_rsa_dir }}/easyrsa build-ca nopass"
      chdir: "{{ openvpn_dir }}/easy-rsa"
      creates: "{{ openvpn_dir }}/easy-rsa/pki/ca.crt"
  - name: easy-rsa gen-dh
    command: 
      cmd: "{{ easy_rsa_dir }}/easyrsa gen-dh"
      chdir: "{{ openvpn_dir }}/easy-rsa"
      creates: "{{ openvpn_dir }}/easy-rsa/pki/dh.pem"

  - name: easy-rsa gen-crl
    command: 
      cmd: "{{ easy_rsa_dir }}/easyrsa gen-crl"
      chdir: "{{ openvpn_dir }}/easy-rsa"
      creates: "{{ openvpn_dir }}/easy-rsa/pki/crl.pem"

  - name: openvpn genkey
    command: 
      cmd: "openvpn --genkey --secret {{ openvpn_dir }}/easy-rsa/pki/ta.key"
      creates: "{{ openvpn_dir }}/easy-rsa/pki/ta.key"

  - name: easy-rsa server nopass
    command: 
      cmd: "{{ easy_rsa_dir }}/easyrsa build-server-full server nopass"
      chdir: "{{ openvpn_dir }}/easy-rsa"
      creates: "{{ openvpn_dir }}/easy-rsa/pki/issued/server.crt"

  - name: "Copy files to {{ openvpn_dir }}/server"
    copy:
      src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
      dest: "{{ openvpn_dir }}/server/{{ item | basename }}"
      mode: "0644"
      remote_src: true
    loop:
      - ca.crt
      - dh.pem
      - ta.key
      - private/ca.key
      - private/server.key
      - issued/server.crt

  - name: Copy files to /etc/openvpn
    copy:
      src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
      dest: "{{ openvpn_dir }}/{{ item | basename }}"
      mode: "0640"
      remote_src: yes
    loop:
      - ca.crt
      - ta.key

  - name: Copy server.conf
    template:
      src: server.conf.j2
      dest: "{{ openvpn_dir }}/server.conf"
      owner: root
      group: root
      mode: "0644"
    notify:
      - restart openvpn

  - name: Open forwarding
    command:
      cmd: "sysctl -w net.ipv4.ip_forward=1"

